mpc:
  du_threshold: 0.001
  dt: 0.02
  wheel_base: 3.00465
  max_iter: 150
  predict_steps: 20
  max_steer: 1.2217304763960306
  max_dsteer: 3.14
  max_speed: 30.0
  min_speed: -30.0
  max_accel: 8.0
  in_test: false
  control_a: true
  feed_forward: false
  matrix_q: [10.0, 10.0, 2.5, 15.0]
  # matrix_q: [10.0, 10.0, 2.5, 7.5]
  matrix_r: [0.1, 0.01]
  matrix_rd: [0.50, 0.30]
  # test_traj: "/home/xulong/bk/libai"
  # test_traj: "/home/xulong/bk/Hobca"
  test_traj: "/home/xulong/bk/PJSO"
  # test_traj: "/home/xulong/bk/teb"
  # test_traj: "/home/xulong/bk/minco_huifu"
  # matrix_rd: [0.01, 1.0]
